--- 
apiVersion: v1
kind: Pod
metadata: 
  name: volpod
spec: 
  containers: 
    - 
      image: nginx
      name: volpod
      volumeMounts: 
        - 
          mountPath: /mydata
          name: pv01
  volumes: 
    - 
      name: pv01
      persistentVolumeClaim: 
        claimName: pv01-claim
